### PR TITLE
Edited crop yield tutorial

### PR DESCRIPTION
**Pull request by kathrine-swe**

### CODE REVIEW

**Comment by karla-dl** [comment]
@samanthaandrews please review this on behalf of the Guild! The main four criteria to look out for are: 
Use only publicly available core products

1. Use only publicly available core products
2. Are in Jupyter Notebook format (with supporting training files)
3. Run end-to-end without error 
4. Follow documentation best practices

For more information on reviewing tutorials, look here: 
https://descarteslabs.atlassian.net/wiki/spaces/DG/pages/7045121/Adding+Tutorials

Thanks in advance!

**Comment by samanthaandrews** [comment]
Since this PR has no description, I'm trying to figure out what exactly changed. My git diff shows the following:

```
--- a/crop_yield/descartes-labs-crop-yield-demo.ipynb
+++ b/crop_yield/descartes-labs-crop-yield-demo.ipynb
@@ -1,1280 +1,970 @@
 {
-  "nbformat": 4,
-  "nbformat_minor": 0,
-  "metadata": {
-    "kernelspec": {
-      "display_name": "Python 3",
-      "language": "python",
-      "name": "python3"
-    },
-    "language_info": {
-      "codemirror_mode": {
-        "name": "ipython",
-        "version": 3
-      },
-      "file_extension": ".py",
-      "mimetype": "text/x-python",
-      "name": "python",
-      "nbconvert_exporter": "python",
-      "pygments_lexer": "ipython3",
-      "version": "3.7.3"
-    },
-    "colab": {
-      "name": "Descarttes Labs Crop Yield Demo.ipynb",
-      "version": "0.3.2",
-      "provenance": [],
-      "collapsed_sections": [],
-      "include_colab_link": true
-    }
+ "cells": [
+  {
+   "cell_type": "markdown",
+   "metadata": {},
```

@karla-dl do you know by chance what the objective was in editing this tutorial? Or perhaps @kathrine-swe can still add a description?

I ran the code and it works fine, but I did have to `pip install folium` and use Python version 3.6.5 instead of the default 3.7.

**Comment by samanthaandrews** [comment]
Ok I have done some more testing and fixed breaking errors. I received several deprecation warnings that look like this:

```
/opt/conda/lib/python3.7/site-packages/jinja2/runtime.py:318: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping

/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py:1151: DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
  self, resource_name

/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py:1151: DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
  self, resource_name

/opt/conda/lib/python3.6/site-packages/folium/folium.py:426: FutureWarning: The choropleth  method has been deprecated. Instead use the new Choropleth class, which has the same arguments. See the example notebook 'GeoJSON_and_choropleth' for how to do this.
  FutureWarning

/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py:1151: DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
  self, resource_name

/opt/conda/lib/python3.7/site-packages/descarteslabs/client/deprecation.py:45: DeprecationWarning: The parameter `nbits` has been deprecated and will be removed in future versions.
  warnings.warn(msg, DeprecationWarning)
```
@jmileson do any of these look like things we should fix? That last one about nbits maybe?

I also received a runtime warning when running this block:

```
dl.scenes.display(old_image_stack[-1], bands_axis=-1, colormap='viridis')
dl.scenes.display(new_image_stack[-1], bands_axis=-1, colormap='viridis')

/opt/conda/lib/python3.6/site-packages/descarteslabs/scenes/_display.py:191: RuntimeWarning: overflow encountered in short_scalars
  disp /= vmax - vmin
```

**Comment by jmileson** [comment]
Not sure we can suppress the first set of warnings nicely, I'm not too worried about it.

You can get rid of the `RuntimeWarning` by changing the `dtype` of `old_image_stack` to `Int32`

``` python
old_image_stack, old_meta = dl.raster.stack(
    ids,
    bands=bands,
    dltile=tile,
    cutline=shape,
    data_type="Int32"
)
```

**Comment by samanthaandrews** [comment]
@jmileson Thank you! That did fix the runtime warning. I committed the change. Approving now.

**Review by samanthaandrews — APPROVED** [review]
Note: I had to install Folium in order to run this tutorial -- @karla-dl said we are coming up with a standardized way to let users know what they will need to install

**Pull request merged**
